### ISSUE TITLE
(reactxp) create-rx-app: App Could not find plugin "proposal-numeric-separator"

### ISSUE THREAD

**Issue by mgolden6** [a-tarasyuk/create-rx-app#18]
1. I used `npm init rx-app AppName` from the [instructions](https://github.com/a-tarasyuk/create-rx-app) to create a reactxp App
2. I used `npm run start:web` to test it, but it failed with the following error: 

> Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it.

@alariej [issue & solution](https://github.com/a-tarasyuk/create-rx-app/issues/17) solved my problem.

I detailed the [4 steps](https://github.com/a-tarasyuk/create-rx-app/issues/17#issuecomment-615905917).

I am new to developing, so not sure how this works, but would it be possible for someone to add the following 2 lines to `\node_modules\@babel\preset-env\lib\available-plugins.js`, and make sure that plugin is installed when calling `npm init rx-app` so others don't run into this problem when trying to create-rx-app?

1. `var _pluginProposalNumericSeparator = _interopRequireDefault(require("@babel/plugin-proposal-numeric-separator"))` with the other var's

2. `"proposal-numeric-separator": _pluginProposalNumericSeparator.default` with the others in var _default so it gets exported with `default`

**Comment by a-tarasyuk** [comment]
The issue should be fixed in v0.6.19
