### ISSUE TITLE
create-rx-app creates an app but throws Babel Errors

### ISSUE THREAD

**Issue by ssossou** [a-tarasyuk/create-rx-app#19]
$ yarn start:web
yarn run v1.15.2
$ cross-env platform=web webpack-dev-server --config=web/webpack/dev.js --progress --colors --mode=development
Starting type checking service...
10% building 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:9999/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/sedote.sossou/sourceCode/yamahaPoc/src
11% building 11/15 modules 4 active /Users/sedote.sossou/sourceCode/yamahaPoc/node_modules/webpack-dev-server/client/utils/sendMessage.jsℹ ｢wdm｣: wait until bundle finished: /
98% after emittingType checking in progress...
✖ ｢wdm｣:    37 modules

ERROR in ./src/index.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/sedote.sossou/sourceCode/yamahaPoc/src/index.tsx: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/Users/sedote.sossou/sourceCode/yamahaPoc/node_modules/@babel/preset-env/lib/index.js")
    at getPlugin (/Users/sedote.sossou/sourceCode/yamahaPoc/node_modules/@babel/preset-env/lib/index.js:67:11)
    at /Users/sedote.sossou/sourceCode/yamahaPoc/node_modules/@babel/preset-env/lib/index.js:258:62
    at Array.map (<anonymous>)
    at /Users/sedote.sossou/sourceCode/yamahaPoc/node_modules/@babel/preset-env/lib/index.js:258:43
    at /Users/sedote.sossou/sourceCode/yamahaPoc/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /Users/sedote.sossou/sourceCode/yamahaPoc/node_modules/@babel/core/lib/config/full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/sedote.sossou/sourceCode/yamahaPoc/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at step (/Users/sedote.sossou/sourceCode/yamahaPoc/node_modules/gensync/index.js:254:32)
ℹ ｢wdm｣: Failed to compile.
No type errors found
Version: typescript 3.8.3
Time: 2597ms
![Screen Shot 2020-06-08 at 3 08 24 PM](https://user-images.githubusercontent.com/340387/84070290-e7aa2780-a999-11ea-8986-f371ccd11f50.png)

**Comment by ssossou** [comment]
@a-tarasyuk , i am sorry i can't find the duplicate ticket. can you please point me to it so i can read the resolution?

**Comment by a-tarasyuk** [comment]
#18. Actually you don't need to install `proposal-numeric-separator`, just need to update babel and related packages to babel to the latest versions. The latest version of the template should resolve that.
