### ISSUE TITLE
Support for Dynamic Imports

### ISSUE THREAD

**Issue by alariej** [a-tarasyuk/create-rx-app#8]
Hi, does your project generator support "dynamic imports", similar to what the ReactXP TodoList sample does for fonts and images:
https://github.com/Microsoft/reactxp/tree/be7d50db098a205ffeec74f617b30d14d832e7b8/samples/TodoList/src/ts/modules/fonts
https://github.com/Microsoft/reactxp/blob/be7d50db098a205ffeec74f617b30d14d832e7b8/samples/TodoList/src/ts/modules/README.md
If not, do you have a suggestion on how to do code splitting when using create-rx-app?
Thanks!

**Comment by a-tarasyuk** [comment]
@alariej 

> "dynamic imports"

Do you mean import based on platform?

**Comment by alariej** [comment]
Yes, based on platform: Web, Native, Windows...

**Comment by a-tarasyuk** [comment]
@alariej Yes, it is possible.

```shell 
Button
  - Button.tsx
  - Button.android.tsx
  - Button.ios.tsx
  - Button.windows.tsx
```

`Button.tsx` is the Web version and is default version for all platforms if any of them were not created. `.android.tsx`, `ios.tsx`, `.windows.tsx` - can be combined to `.native.tsx` and all native platforms (Android, iOs, and Windows) will use code from that file.

To import code you need use usual import, and Babel/RN/RNW will resolve appropriate file, you don't need to do any additional work for that.
 
```typescript
import Button from './Button/Button';
```

**Comment by alariej** [comment]
Just tested it (on web and android), works perfectly! Many thanks for the quick response and this very useful repo!

**Comment by a-tarasyuk** [comment]
@alariej welcome! ;).
