### ISSUE TITLE
no eslint configuration found error when use `--javascript`

### ISSUE THREAD

**Issue by geminiyellow** [a-tarasyuk/create-rx-app#9]
simply create a project by create-xp-app and run `npm run build:web`. then

```
ERROR in ./src/index.js
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: No ESLint configuration found.

```

**Comment by a-tarasyuk** [comment]
@geminiyellow I've created the new JavaScript project, and ESLint works fine. Could you provide more information? 

Steps which I did 

1. `npx create-rx-app AppName`
2. `cd AppName`
3. `npm run build:web`

You can try to remove node_modules and re-install dependencies

**Comment by geminiyellow** [comment]
@a-tarasyuk thanks for your reply, 
but i think you did not got the what i said, 
your 1 step , is create a typescript project , not javascript project.
like this issue title, just modify it to 

`create-rx-app AppName --javascript`

you can see the options by type `create-rx-app --help`

```
> create-rx-app --help
Usage: create-rx-app <project-directory> [options]

Options:
  --javascript    generate project in JavaScript
  --skip-install  don't automatically install dependencies
  --skip-jest     don't automatically add Jest configuration
  --skip-yarn     don't use Yarn for managing dependencies
  -v, --version   output the version number
  -h, --help      output usage information
```

and cause the error reason is missing `_eslintrc` . copy it from template , and everything is ok.

**Comment by geminiyellow** [comment]
hmm... i check it again, everything looks good.
sorry for this and i really want to know what cause this error.
but code everything looks good.
close and sorry again.

**Comment by a-tarasyuk** [comment]
@geminiyellow ok.
